# This is a basic workflow to help you get started with Actions

name: Comunicador de la legión

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  workflow_dispatch:
    inputs:
      villano:
        description: "Que villano envía el mensaje"
        required: true
        type: choice
        options:
          - "Lex Luthor"
          - "Joker"
          - "Darkseid"
          - "Brainiac"

      prioridad:
        description: "Prioridad del mensaje"
        required: true
        type: choice
        options:
          - "Alta"
          - "Media"
          - "Baja"

      mensaje:
        description: "Mensaje a enviar"
        required: false
        default: "Mensaje por defecto"
        type: string

jobs:
  transmitir-mensaje:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir inputs
        run: |
          echo: "Inputs: "
          echo: ""
          echo: "Villano: ${{ inputs.villano }}"
          echo: "Mensaje: ${{ inputs.mensaje }}"
          echo: "Prioridad: ${{ inputs.prioridad }}"
